name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract Archive and Install
        run: |
          tar -xvf n.tar.gz
          sh install.sh

      - name: Start Node App with Timeout
        run: |
          timeout 120s node main.js || echo "Job timed out"

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          echo $(date) > last_run.txt
          git add last_run.txt
          git commit -m "Auto-restart workflow: $(date)"
          git push
